import { defaultUserType } from '../user';
export const defaultUser:defaultUserType= {
    login: "Adem54",
    id: 48107744,
    node_id: "MDQ6VXNlcjQ4MTA3NzQ0",
    avatar_url: "https://avatars.githubusercontent.com/u/48107744?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Adem54",
    html_url: "https://github.com/Adem54",
    followers_url: "https://api.github.com/users/Adem54/followers",
    following_url: "https://api.github.com/users/Adem54/following{/other_user}",
    gists_url: "https://api.github.com/users/Adem54/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Adem54/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Adem54/subscriptions",
    organizations_url: "https://api.github.com/users/Adem54/orgs",
    repos_url: "https://api.github.com/users/Adem54/repos",
    events_url: "https://api.github.com/users/Adem54/events{/privacy}",
    received_events_url: "https://api.github.com/users/Adem54/received_events",
    type: "User",
    site_admin: false,
    name: "Adem Erbas",
    company: "Always developing",
    blog: "www.ademerbas.com",
    location: "Norway",
    email: null,
    hireable: null,
    bio: "Always learning",
    twitter_username: "@adem54",
    public_repos: 61,
    public_gists: 0,
    followers: 2,
    following: 5,
    created_at: "2019-02-28T22:51:06Z",
    updated_at: "2022-09-14T10:06:23Z"
  }